export { default as Items } from './Items'
export { default as Home } from './Home'
export { default as Pokemons } from './Pokemons'
export { default as Pokemon } from './Pokemon'
export { default as Type } from './Type'
export { default as Map } from './Map'